services:
  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment: 
      - DJANGO_SERVER_ADDR=django-app:8000
    ports:
      - "80:80"
    depends_on:
      - django-app
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
  django-app:
    build: django
    restart: always
    ports: 
      - '8000:8000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/django-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: python3 manage.py runserver 0.0.0.0:8000