version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_qz
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=qz
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
      - MYSQL_USERNAME=qzdev
      - MYSQL_PASSWORD=Qz123456
      - MYSQL_ADDRESS=sh-cynosdbmysql-grp-cjnx256e.sql.tencentcdb.com:21912
networks:
  default:
    external:
      name: wxcb0
